module instruction_memory(	input  logic [31:0] read_address,
							output logic [31:0] read_data
							);

    parameter logic [31:0] start_address = 32'h00001000;
	/// sample code for now but later replace it by read the hex file directly which will be generated by a c code using a riscv gcc tool
    always_comb begin
        case (read_address)
            start_address          : read_data = 32'h00500513;  // addi x10, x0, 5     ; a = 5
            start_address + 32'h04 : read_data = 32'h00600593;  // addi x11, x0, 6     ; b = 6
            start_address + 32'h08 : read_data = 32'h00B58633;  // add  x12, x11, x10  ; c = a + b
            start_address + 32'h0C : read_data = 32'h0000006F;  // jal x0, 0           ; infinite loop
            default                : read_data = 32'hDEADBEEF;
        endcase
    end

	
endmodule
